In [6]:
import tweepy
import TwitterCredentials as keys
import pandas as pd

auth = tweepy.OAuthHandler(keys.consumer_API_key, keys.consumer_API_secret_key)
auth.set_access_token(keys.access_token, keys.access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

#cursor objects for each news source
wsj = tweepy.Cursor(api.user_timeline, screen_name='wsj', tweet_mode='extended')
cnn = tweepy.Cursor(api.user_timeline, screen_name='CNN', tweet_mode='extended')
nyt = tweepy.Cursor(api.user_timeline, screen_name='nytimes', tweet_mode='extended')
fox = tweepy.Cursor(api.user_timeline, screen_name='foxnews', tweet_mode='extended')

#define empty lists to hold each tweet
wsjlist = []
cnnlist = []
nytlist = []
foxlist = []

#store each tweet in the cursor object in the corresponding list
for tweet in wsj.items(900):
    wsjlist.append(tweet)

for tweet in cnn.items(900):
    cnnlist.append(tweet)
    
for tweet in nyt.items(900):
    nytlist.append(tweet)
    
for tweet in fox.items(900):
    foxlist.append(tweet)
    
#store data as a data frame
df = pd.DataFrame({"Wall Street Journal": wsjlist, "CNN": cnnlist, "New York Times": nytlist, "Fox": foxlist})

In [7]:
df

,Wall Street Journal,CNN,New York Times,Fox
0,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
1,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
2,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
3,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
4,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
...,...,...,...,...
895,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
896,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
897,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
898,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...
899,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...,Status(_api=<tweepy.api.API object at 0x000002...

In [2]:
pip install tweepy

Collecting tweepy
  Downloading tweepy-3.8.0-py2.py3-none-any.whl (28 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: requests>=2.11.1 in c:\users\abbyc\anaconda3\lib\site-packages (from tweepy) (2.22.0)
Requirement already satisfied: PySocks>=1.5.7 in c:\users\abbyc\anaconda3\lib\site-packages (from tweepy) (1.7.1)
Requirement already satisfied: six>=1.10.0 in c:\users\abbyc\anaconda3\lib\site-packages (from tweepy) (1.14.0)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.0-py2.py3-none-any.whl (147 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abbyc\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\abbyc\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\abbyc\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\abbyc\anaconda3\lib\site-packages (from requests>=2.11.1->tweepy) (2.8)
Installing collected packages: oauthlib, requests-oauthlib, tweepy
Successfully installed oauthlib-3.1.0 requests-oauthlib-1.3.0 tweepy-3.8.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
#function to convert the tweepy object to text
def totext(tweet):
    return tweet.full_text

#define new data frame to hold texts of tweets
dfnew = pd.DataFrame({"Wall Street Journal": [], "CNN": [], "New York Times": [], "Fox": []})

#map above function to each column in df
dfnew["Wall Street Journal"] = df["Wall Street Journal"].map(totext)
dfnew["CNN"] = df["CNN"].map(totext)
dfnew["New York Times"] = df["New York Times"].map(totext)
dfnew["Fox"] = df["Fox"].map(totext)

In [9]:
dfnew

,Wall Street Journal,CNN,New York Times,Fox
0,"How many times can a 4-year-old watch ""Frozen""...","President Trump fired Michael Atkinson, the in...","Kobe Bryant, Tamika Catchings, Tim Duncan and ...",https://t.co/YIXb9Ums2U
1,Alabama and Missouri became the latest states ...,Nurse Letha Love traveled to New York from Atl...,What does Larry David fear most right now? “An...,https://t.co/VorFtxltmN
2,Farms and orchards across the U.S. are scrambl...,According to figures released on Saturday by t...,"""It’s a big country, so there’s always going t...",https://t.co/sUVE5AVQlF
3,Hello? He-he-lo?\nHe-he-he-lo? Lo? Lo? (Damn)\...,Democratic presidential front-runner Joe Biden...,Join @NYTStyles in an eco-therapeutic meditati...,https://t.co/QEfH3CMMXp
4,Paper towels. Cloth towels. Dryers. How you dr...,While the number of active cases in Spain cont...,Thousands of prisoners in Britain will be gran...,https://t.co/AKdwRY4EHh
...,...,...,...,...
895,Occidental Petroleum reached a truce with Carl...,Ken Shimura died of pneumonia caused by novel ...,Rent collections are being delayed. Water rest...,Neil Armstrong's Apollo 11 spacecraft ID plate...
896,He had finished packing and was ready for his ...,People with heart conditions who live in areas...,No visitors. Induced labor. Converted delivery...,".@SecPompeo: ""The sanctions that will be reimp..."
897,Hertz—awash in idle rental cars as the travel ...,Some of the most critical US military commande...,RT @JamesStewartNYT: After four stock market c...,".@KarlRove on #Midterms2018: ""People are wildl..."
898,"As coronavirus spreads across the world, gover...","“It’s a medical war zone,” says a doctor at Br...",One man died and 16 people were injured after ...,Vanna White describes how she copes with tough...
899,"Amid the coronavirus pandemic, tackling wills,...",A Phoenix police commander was killed and two ...,Prime Minister Boris Johnson has tested positi...,"Trump amps up Venezuelan crackdown, sanctions ..."

In [5]:
dfnew.to_csv('dataset1.csv')